### ISSUE TITLE
build conda package

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/RESCRIPt#19] opened 2020-05-30 03:06 UTC
see here: https://dev.qiime2.org/latest/tutorials/conda-tutorial/

**Comment by thermokarst** [comment] 2020-10-28 15:51
I believe this has been addressed in several PRs, and can probably be closed now.

**Comment by mirand863** [comment] 2023-07-11 08:50
Hi,

I started working on this issue.

My first idea was to upload the package on bioconda, but the problem is that qiime2 is a dependency and it is in a channel that is not a main conda channel, which apparently is not supported on bioconda. I see two possible solutions:

1. Not list qiime2 and modify the import test to not use qiime2, but the qiime2 installation is still covered in the documentation and users can install rescript with `conda install -c bioconda rescript` in an environment with qiime2 pre-installed.
2. Upload the package to conda-forge, since there it seems it is possible to use non-default conda channels and all dependencies could be installed along with rescript using `conda install -c conda-forge rescript`.

What are your thoughts?

**Comment by misialq** [comment] 2023-07-11 09:32
Hey @mirand863,

Thanks for your message! Actually, we are already building the conda packages. They are being pushed to our custom conda channels though, e.g. https://packages.qiime2.org/qiime2/2023.5/tested/ for the last 2023.5 release. Hence, I think we probably can close this issue as was mentioned above already.

**Comment by mirand863** [comment] 2023-07-11 10:07
> Hey @mirand863,
> 
> Thanks for your message! Actually, we are already building the conda packages. They are being pushed to our custom conda channels though, e.g. https://packages.qiime2.org/qiime2/2023.5/tested/ for the last 2023.5 release. Hence, I think we probably can close this issue as was mentioned above already.

Hi,

Thank you for the response! I was not aware that it was being shipped in the qiime2 channel. Good to know.

Best regards,
Fabio

**Closed** 2024-06-07 12:35 UTC
